### ISSUE TITLE
Not getting it to run

### ISSUE THREAD

**Issue by albrox** [joergschultzelutter/enpasstokeepass#1]
Thank you for this project.

I'm trying to get it to run, but I am failing so far.

I have created an empty database and ideally I would try to run it without any key file and without any password.

I would simply move the data from Enpass to StromVox and then import it from there.

Is a key file and or password necessary?

I do get the an error while I also do not really know how to pass the key file which I have created earlier.

**Comment by joergschultzelutter** [comment]
Hi, thanks for your inquiry. 

I have updated the repo's README.md with some sample instructions on how to use the program. In addition, I introduced a repo-specific ```requirements.txt``` file; seems as if all ```pykeepass``` versions 4.0.3 and later cannot properly process OTP content (in the way I used for writing that content to keepass).

I haven't tried a password-less Keepass file import yet. However, a keyfile is NOT required.

Please install the proper ```pykeepass``` version and give it another try. I just verified that the program still seems to work with the latest Enpass version.

**Comment by albrox** [comment]
Thank you for such fast help! I made it further. When executing, the following error occurs:

```
2023-11-28 01:14:32,754 enpasstokeepass -INFO- Processing entry 'disney'
Traceback (most recent call last):
  File "/Users/username/Documents/GitHub/enpasstokeepass/enpasstokeepass.py", line 316, in <module>
    newentry.set_custom_property(
  File "/Users/username/Library/Python/3.9/lib/python/site-packages/pykeepass/entry.py", line 240, in set_custom_property
    assert key not in reserved_keys, '{} is a reserved key'.format(key)
AssertionError: Title is a reserved key
```

**Comment by albrox** [comment]
Update: I got it to work by removing the "Title" everywhere in the JSON File. Thank you again!

**Comment by joergschultzelutter** [comment]
Interesting - thank you for your feedback. 

I never encountered this "Title" issue with my Enpass exports but your Enpass database's content obviously looks different 😄. 
I will update this quick hack code over the weekend, thus removing the issue for future users.

**Comment by albrox** [comment]
Thank you again for fixing it that fast.

What I also encountered is that some data definitely is missing.

For one entry for example only the passport was transferred and not the username even though it does exist in Enpass and in the export.
