### ISSUE TITLE
subcategory = _templates[1] does not exist if no "." is in template_type

### ISSUE THREAD

**Issue by whulshof** [joergschultzelutter/enpasstokeepass#7]
If one has created a private Category, enpass fills template_type with a uuid without dot. Then the subcategory does not exist and the script fails.
Traceback (most recent call last):

  File "/Volumes/Case-Sens/voodoo/enpasstokeepass2/enpasstokeepass2.py", line 231, in <module>
    subcategory = _templates[1]
IndexError: list index out of range

**Comment by whulshof** [comment]
By removing the UUID and replacing it by "Device.default" in some 20 entries, I was able to get the script running to the end and writing the keepasss file.

Great script by the way. I thought to do the conversion by hand, but 600 entries is too much!  -:)

**Comment by joergschultzelutter** [comment]
Interesting - it's the first time that I hear about this "private category" function. Any guidance on how to enable / activate it? I can then use it with one of my test Enpass databases. FWIW - my dev environment is on MacOS, but I can check the Windows version, too.

Ideally, please provide an anonymized JSON export file snippet and/or screen shots which may help in identifying the issue. As Enpass' database export format is not properly documented, I need to reverse-engineer the data import. Sorry for the mess :-)

**Comment by whulshof** [comment]
hmmm, I just removed the json file from my systems, because it is a security risk to let it stay there. But it is quite simple: instead of for instance "login.default", the "template_type" entry has : "UUID" without any dot (".") in it. 
An entry that causes error is for instance:
{ ...
"subtitle": "OutdoorEAP110",
"template_type": "74a7f537-974c-4bdb-893e-0108dd7f9f5e",
}.

I just changed these "UUID" values with "Device.default" in the json file to solve it.

**Comment by whulshof** [comment]
About how I got the Device group in Enpass I don't know anymore. I started with a keepass file and converted to encase years ago. Am not sure that was the cause.

**Comment by joergschultzelutter** [comment]
OK, I think I got the general gist. These are the categories which are supported by  default in Enpass. Note that you cannot add your very own entry but only enable/disable the entries. 

![Monosnap 2024-01-22 13-24-30](https://github.com/joergschultzelutter/enpasstokeepass/assets/76180229/cd5c20e4-201a-4c5a-95c1-3a80253eb2ec)

I assume that by importing a Keepass file to Enpass, one is able to generate personalized categories which cannot be maintained in Enpass but are exported as uuid.

My suggestion for this fix is the following: Whenever I encounter a 'uuid' template_type, I am going to replace it with a standard template type category from Enpass.
The attached demo file will be used for my tests. Is my assumption correct that I only need to change the template_type setting to a uuid value in order to crash the program?
[otp.json](https://github.com/joergschultzelutter/enpasstokeepass/files/14010101/otp.json)

**Comment by whulshof** [comment]
Hi Jörg,

I think, that is a very good way of working around this problem.
Yes, only a value without dot in it, I think. It is right after the split in your program that the error comes up.

**Comment by joergschultzelutter** [comment]
Thanks Willem for your feedback. Dependent on the "personal" category structure used by Enpass, I might be able to transfer the original category branch back to Keepass. I will create a simple Keepass file with one entry and 1..n subcategories and then first try to import that entry in Enpass, followed by an export from Enpass afterwards. If the (sub)category structure is salvageable, then let's try to migrate it - otherwise, I will go for a default Enpass category and assign it to these entries.

**Comment by whulshof** [comment]
O, But my conversion is 100% a OK now. Don't put in extra effort for the keepass category. I just mentioned the error, so you could improve your great script.
Thanks again for your hard work. It saved me some days of copy paste on my phone.

**Comment by joergschultzelutter** [comment]
For documentation purposes: I created a KeepassXC file with a 4-tiered folder structure, having the 4th folder contain a single entry: The file looks like this:

```
{
    "folders": [
        {
            "icon": "1008",
            "parent_uuid": "",
            "title": "Root",
            "updated_at": 1705933436,
            "uuid": "ec4dc730-a2b2-4208-b669-d121c1c66653"
        },
        {
            "icon": "1008",
            "parent_uuid": "ec4dc730-a2b2-4208-b669-d121c1c66653",
            "title": "Group 1",
            "updated_at": 1705933436,
            "uuid": "8a8ebd20-f241-42e9-baac-51e88e72ad81"
        },
        {
            "icon": "1008",
            "parent_uuid": "8a8ebd20-f241-42e9-baac-51e88e72ad81",
            "title": "Group 2",
            "updated_at": 1705933436,
            "uuid": "502e2f0b-6dd6-4e52-82bc-d2e82fdbe6ec"
        },
        {
            "icon": "1008",
            "parent_uuid": "502e2f0b-6dd6-4e52-82bc-d2e82fdbe6ec",
            "title": "Group 3",
            "updated_at": 1705933436,
            "uuid": "c0ad22a0-8676-4552-a511-993f31689896"
        },
        {
            "icon": "1008",
            "parent_uuid": "c0ad22a0-8676-4552-a511-993f31689896",
            "title": "Group 4",
            "updated_at": 1705933436,
            "uuid": "fa312c20-6b16-4319-971d-2e45f6c587a7"
        }
    ],
    "items": [
        {
            "archived": 0,
            "auto_submit": 1,
            "category": "login",
            "createdAt": 1705933436,
            "favorite": 0,
            "fields": [
                {
                    "deleted": 0,
                    "label": "UserName",
                    "order": 1,
                    "sensitive": 0,
                    "type": "username",
                    "uid": 10,
                    "updated_at": 1705933436,
                    "value": "Test",
                    "value_updated_at": 1705933436
                },
                {
                    "deleted": 0,
                    "label": "E-mail",
                    "order": 2,
                    "sensitive": 0,
                    "type": "email",
                    "uid": 12,
                    "updated_at": 1705933436,
                    "value": "",
                    "value_updated_at": 1705933436
                },
                {
                    "deleted": 0,
                    "label": "Password",
                    "order": 3,
                    "sensitive": 1,
                    "type": "password",
                    "uid": 11,
                    "updated_at": 1705933436,
                    "value": "Test",
                    "value_updated_at": 1705933436
                },
                {
                    "deleted": 0,
                    "label": "Website",
                    "order": 4,
                    "sensitive": 0,
                    "type": "url",
                    "uid": 13,
                    "updated_at": 1705933436,
                    "value": "",
                    "value_updated_at": 1705933436
                },
                {
                    "deleted": 0,
                    "label": "ADDITIONAL DETAILS",
                    "order": 5,
                    "sensitive": 0,
                    "type": "section",
                    "uid": 101,
                    "updated_at": 1705933436,
                    "value": "",
                    "value_updated_at": 1705933436
                },
                {
                    "deleted": 0,
                    "label": "Phone number",
                    "order": 6,
                    "sensitive": 0,
                    "type": "phone",
                    "uid": 14,
                    "updated_at": 1705933436,
                    "value": "",
                    "value_updated_at": 1705933436
                },
                {
                    "deleted": 0,
                    "label": "One-time code",
                    "order": 7,
                    "sensitive": 0,
                    "type": "totp",
                    "uid": 102,
                    "updated_at": 1705933436,
                    "value": "",
                    "value_updated_at": 1705933436
                },
                {
                    "deleted": 0,
                    "label": "Security question",
                    "order": 8,
                    "sensitive": 0,
                    "type": "text",
                    "uid": 15,
                    "updated_at": 1705933436,
                    "value": "",
                    "value_updated_at": 1705933436
                },
                {
                    "deleted": 0,
                    "label": "Security answer",
                    "order": 9,
                    "sensitive": 1,
                    "type": "text",
                    "uid": 16,
                    "updated_at": 1705933436,
                    "value": "",
                    "value_updated_at": 1705933436
                }
            ],
            "folders": [
                "fa312c20-6b16-4319-971d-2e45f6c587a7"
            ],
            "icon": {
                "fav": "",
                "image": {
                    "file": "misc/login"
                },
                "type": 1,
                "uuid": ""
            },
            "note": "Hello World",
            "subtitle": "Test",
            "template_type": "login.default",
            "title": "Test Entry",
            "trashed": 0,
            "updated_at": 1705933436,
            "uuid": "1f919317-c627-4360-8db4-1e84905c4a91"
        }
    ]
}
```

The "folders" uuid reference at the end of the file points to the "folders" structure at the beginning of the file, meaning that one could reconstruct that folder structure from the export file. However, the "template_type" field seems to be set properly. Maybe the Enpass guys changed this behavior in the past. After all, this is a reverse-engineering approach :smile:

Nevertheless, I will check if the folder structure can be salvaged from the input file and add an additional safe guard in case it cannot be resolved AND the template_type still contains a UUID value.

Thank you!

**Comment by joergschultzelutter** [comment]
I've deployed a new new release 1.1.3 which should fix the issue in the following way:

* if a UUID is detected in the template_type field, `enpasstokeepass` will create a `Miscellaneous` category for this entry

In theory, it should also be able to copy the whole folder structure but as Enpass (ab)uses its tag structure also for creating folders, this might be a task for another day.

**Comment by whulshof** [comment]
I'm getting the following Traceback:

2024-01-23 09:36:16,253 enpasstokeepass2 -INFO- Processing entry 'Freenas forum'
Traceback (most recent call last):
  File "/Volumes/Case-Sens/voodoo/enpasstokeepass2/enpasstokeepass2.py", line 298, in <module>
    if "." in template_type and not is_uuid(template_type):
  File "/Volumes/Case-Sens/voodoo/enpasstokeepass2/enpasstokeepass2.py", line 155, in is_uuid
    uuid.UUID(my_uuid)
AttributeError: 'str' object has no attribute 'UUID'

**Comment by joergschultzelutter** [comment]
Weird; ok - I'll recheck this issue later on today. 

Reopening ticket.

**Comment by joergschultzelutter** [comment]
Release [1.1.4](https://github.com/joergschultzelutter/enpasstokeepass/releases/tag/1.1.4) resolves the issue.

**Comment by whulshof** [comment]
Yes, it does!
