### ISSUE TITLE
Retain the creation/modification date?

### ISSUE THREAD

**Issue by Tekl** [joergschultzelutter/enpasstokeepass#9]
Hi,

is it possible to enhance the script, so that the creation date of the Enpass entries is transferred to the Keepass tresor?

**Comment by joergschultzelutter** [comment]
I am not sure if this is supported by the underlying `pykeepass` library. See [this page](https://github.com/libkeepass/pykeepass) for details. FWIW, this is mentioned in `enpasstokeepass`' out-of-scope documentation:

    As part of the conversion, all entries will lose their original creation date as it does not seem to be possible to set that value via pykeepass

Modifying the `credchange_date` value **_might_** do the trick but I need to investigate this as there is no official method for setting that time stamp. For now, I'll keep the ticket open and have a look at this tomorrow.

**Comment by joergschultzelutter** [comment]
Well ... I tried my best but unfortunately, the answer is still 'no'. Have a look at `pykeepass`' code:

![baseelement py 2024-01-24 22-42-41](https://github.com/joergschultzelutter/enpasstokeepass/assets/76180229/10cf63a4-02d3-4c24-8677-487c5cfa3f1d)

In short terms: the only time step that can be set is the entry's `expiry date` setting. The values for both `creation date` and `last modification date` are both hardcoded to the time when the entry is created via `pykeepass`. Sorry, but there is no workaround.

**Comment by Tekl** [comment]
Okay. Thanks for your investigations.
